[workspace]
members = ["compiler"]

[package]
name = "something"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler = {path = "compiler"}
clap = "2.34.0"

